# Generated by Django 4.2.5 on 2023-10-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement1', '0002_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
