# Generated by Django 4.2.5 on 2023-10-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement1', '0003_blockedipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
